config/routes.rb
Rails.application.routes.draw do
  resources :users, except: :destroy
  get '/games/game_over', to: 'games#game_over', as: 'game_over'
  get '/games/game_won', to: 'games#game_won', as: 'game_won'
  resources :games
  resources :bosses, only: :show
  # resources :boss_phrases
  # resources :player_phrases
  resources :players, only: :show
  # resources :hands
  resources :card_libraries, only: [:show, :index]
  get '/', to: 'game#index', as: 'main'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boss.rb
class Boss < ApplicationRecord
  has_many :boss_phrases
  has_many :games

  def pick_action
    @randomizer = rand(1..self.boss_phrases.all.size)
    self.boss_phrases.find_by(id: @randomizer)
  end

end

app/models/boss_phrase.rb
class BossPhrase < ApplicationRecord
  belongs_to :boss
end

app/models/card_library.rb
class CardLibrary < ApplicationRecord
  has_many :hands
  has_many :users, through: :hands 
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :boss
  belongs_to :user

  

end

app/models/hand.rb
class Hand < ApplicationRecord
  belongs_to :user
  belongs_to :card_library
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :users
  has_many :player_phrases

  def random_phrase(effect_type)
    @phrases = self.player_phrases.select do |phrase|
      phrase.effect_type == effect_type
    end
    @phrases.sample.phrase
  end

end

app/models/player_phrase.rb
class PlayerPhrase < ApplicationRecord
  belongs_to :player 
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :player
  has_many :hands
  has_many :card_libraries, through: :hands
  has_many :games
end

app/controllers/bosses_controller.rb
class BossesController < ApplicationController

  def show
    @boss = Boss.find_by(id: params[:id])
    @gameid = flash[:game]
    session[:boss_down] = true
  end

end

app/controllers/game_controller.rb
class GameController < ApplicationController

  def index
    session[:boss_down] = true
    render :index
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    @games = Game.all
  end

  def show
    @game = Game.find_by(id: params[:id])
  end

  def new
    @game = Game.new
    # @player_options = Player.all.map{|p| [p.name,p.id]}
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      flash[:boss_down] = true
      redirect_to @game
    else
      flash[:errors] = @game.errors.full_messages
      redirect_to new_game_path
    end
  end

  def update
    session[:boss_down] = false
    @game = Game.find_by(id: params[:id])
    #Logic for action resolution here
    if action_params[:effect_type] == "Attack"
      @game.boss_health -= action_params[:power].to_i
    elsif action_params[:effect_type] == "Heal"
      @game.user_health += action_params[:power].to_i
    end
    flash[:player_phrase] = @game.user.player.random_phrase(action_params[:effect_type])

    #Check for boss death
    #If dead, increment boss and redirect to new page
    #Logic to determine which boss death screen gets shown

    # byebug
    if @game.boss_health.to_i <= 0 #boss death condition
      @game.boss_id += 1
      if @game.boss_id.to_i == 4
        redirect_to game_won_path and return
      end
      @game.boss_health = Boss.find_by(id: @game.boss_id).health
      @game.bosses_defeated += 1
      if @game.user_health.to_i < 20
        @game.user_health = 20
      end
      @game.save
      flash[:game] = @game.id
      redirect_to boss_path(@game.boss) and return
    else
      @boss_action = @game.boss.boss_phrases.sample
      if @boss_action.effect_type == "Attack"
        @game.user_health -= @boss_action.potency.to_i
        if @game.user_health.to_i <= 0
          redirect_to game_over_path and return
        end
      elsif @boss_action.effect_type == "Heal"
        @game.boss_health += @boss_action.potency.to_i
      end
      flash[:boss_phrase] = @boss_action.phrase
      flash[:boss_effect] = @boss_action.effect_type
      flash[:boss_power] = @boss_action.potency
      @game.save

      #refactor here
      if action_params[:quantity] == "1"
        Hand.find_by(id: action_params[:hand_id]).destroy
        User.find_by(id: @game.user_id).hands << Hand.create(user_id: @game.user_id, card_library_id: rand(1..CardLibrary.all.size), quantity: 1)
      else
        Hand.find_by(id: action_params[:hand_id]).update(quantity: (action_params[:quantity].to_i-1))
        User.find_by(id: @game.user_id).hands << Hand.create(user_id: @game.user_id, card_library_id: rand(1..CardLibrary.all.size), quantity: 1)
      end
      redirect_to @game
    end
  end

  def destroy
    byebug
    @game = Game.find_by(id: params[:id])
    @user = @game.user
    @game.destroy
    redirect_to @user
  end

  def game_over
    render :game_over
  end

  def game_won
    render :game_won
  end

  private

  def game_params
    params.require(:game).require(:user_health, :boss_health, :user_id, :boss_id, :image, :bosses_defeated)
  end

  def action_params
    params.require(:hand).permit(:effect_type, :power, :hand_id, :quantity)
  end

end

app/controllers/hands_controller.rb
class HandsController < ApplicationController

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def show
    @player = Player.find_by(id: params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @players = Player.all
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def new
    @user = User.new
    @player_options = Player.all.map{|p| [p.name,p.id]}
  end

  def create
    @user = User.new(player_params)
    flash[:player_phrase] = nil
    flash[:boss_phrase] = nil 
    if @user.save
      @game = Game.create(user_id: @user.id,boss_id: Boss.all.first.id, bosses_defeated: 0, image: "", user_health: @user.player.health, boss_health: Boss.all.first.health)
      3.times do
        @hand = Hand.create(user_id: @user.id, card_library_id: rand(1..CardLibrary.all.size), quantity: 1)
      end
      redirect_to @game
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to edit_user_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:player_id)
  end

  def player_params
    params.permit(:player_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boss_phrases_helper.rb
module BossPhrasesHelper
end

app/helpers/bosses_helper.rb
module BossesHelper
end

app/helpers/card_libraries_helper.rb
module CardLibrariesHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/hands_helper.rb
module HandsHelper
end

app/helpers/player_phrases_helper.rb
module PlayerPhrasesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/game/index.erb
 <span class="start"><%= image_tag "https://i.imgur.com/hiPI4e4.jpg" %>
<%= button_tag(type: "input") do %>
<%= link_to "itDon'tMakeNoSense, assemble!", users_path, method: :get %>
<% end %></span>

app/views/games/game_over.erb
<%= image_tag('https://i.imgur.com/K5s1ECG.jpg', style: "height:100%;width:100%;") %>
<%= button_tag(type: "input", class: "continue") do %>
  <%= link_to "Start a new game", main_path, method: :get, style: "position:relative;left:0%;bottom:0%,width:100%;height:100%;" %>
<% end %>

app/views/games/game_won.erb
<%= image_tag('https://i.imgur.com/z3CODlG.jpg', style: "height:100%;width:100%;") %>
<%= button_tag(type: "input", class: "continue") do %>
  <%= link_to "Start a new game", main_path, method: :get, style: "position:relative;left:0%;bottom:0%,width:100%;height:100%;" %>
<% end %>

app/views/games/index.erb
All games currently being played: <br>
<% @games.each do |game| %>
<%= link_to game.user.name+" versus "+game.boss.name, game_path(game) %><br>
Playing as: <%= game.user.player.name %>
<% end %><br><br>
<%= button_to "Start a new game", new_user_path, method: :get %>

app/views/games/new.erb
New game page <br>

app/views/games/show.erb
<link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">
<% if @game.boss_id == 3 %>
<%= image_tag("https://i.imgur.com/E5gN1eK.gif", style: "position: absolute; border:0px;margin:0px:display:inline;top:0px;height:100%;width:100%;z-index:-10;opacity:.8;") %>
<% elsif @game.boss_id == 2 %>
<%= image_tag("https://i.imgur.com/qvPNZG1.jpg", style: "position: absolute; border:0px;margin:0px:display:inline;top:0px;height:100%;width:100%;z-index:-10;opacity:.9;")%>
<% else %>
<%= image_tag("https://i.imgur.com/GwLzS4w.jpg", style: "position: absolute; border:0px;margin:0px:display:inline;top:0px;height:100%;width:100%;z-index:-10;opacity:.9;")%>
<% end %>
<div class="show">
<section>
<span style="color:white"><%= @game.user.player.name %></span> <span style="color: red"> VS </span><span style="color:white"><%= @game.boss.name %><br></span>
</section>
<div class="player">
  <h2 style="font-family: 'Permanent Marker';font-size:250%;color:white;margin-bottom:0px;">
    <div class="bossquote">
    <span style="color: white">  <% if flash[:boss_phrase] %>
      <%= flash[:boss_phrase] %>
      <% else %>
      <br>
      <% end %>
    </span>
    <% if flash[:boss_phrase] %>
      <% if flash[:boss_effect] == "Attack" %>
      <div class="attack">
      <span style="color: red"> <%= @game.boss.name %> hit you for <%= flash[:boss_power] %>!
      </span>
      </div>
      <% else %>
      <div class="heal">
      <span stlye="color: green"> <%= @game.boss.name %> healed for <%= flash[:boss_power] %>!
      </span>
      </div>
      <% end %>
    <% end %>
    <br><br><br><br><br><br>
</div>
  <%= @game.user.player.name %>: <span style="color:red"> <%= @game.user_health %> health </span><br>
  <span style="color: white">
  <% if flash[:player_phrase] %>
  <%= flash[:player_phrase] %>
  <% else %>
  <br>
  <% end %>
  </span<br><br><br><br>
  </h2>
</div>
<div class="boss">
  <h3><%= @game.boss.name %>: <span style="color:red"> <%= @game.boss_health %> health </span></h3><br>
</div>
<% if session[:boss_down] %>
<div class="bossfade">
<% end %>
<%= image_tag("#{@game.boss.image}", style: "position:fixed;top:2%;left:62%;display:inline;border:0px;") %>
<%= image_tag("#{@game.user.player.battle_image}", style: "position:fixed;bottom:0%;left:2%;display:inline;border:0px;") %>
<% if session[:boss_down] %>
</div>
<% end %>
<p>
  <div class="deck">
<% @game.user.hands.each do |hand| %>
  <div class="card card1">
    <div class="face front" style="background-image: url(<%= hand.card_library.image %>);">
<%= form_for :hand do |f| %>
<%= f.hidden_field :effect_type, value: hand.card_library.effect_type %>
<%= f.hidden_field :power, value: hand.card_library.power %>
<%= f.hidden_field :hand_id, value: hand.id %>
<%= f.hidden_field :quantity, value: hand.quantity %>
 <%= button_to hand.card_library.name, game_path(@game), method: :patch %>
<% end %>
</div>
 </div>
<% end %>
</div>
</p>
</div>

app/views/games/story.erb
This is the story path